[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
external_media_address=18.144.16.82
external_signaling_address=18.144.16.82
local_net=172.31.0.0/16

[twilio]
type=endpoint
context=from-twilio
disallow=all
allow=ulaw,alaw
aors=twilio
transport=transport-udp
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
rtp_keepalive=20

[twilio]
type=aor
max_contacts=1

[twilio_identify]
type=identify
endpoint=twilio
match=54.172.60.0/30
match=54.244.51.0/30
match=54.171.127.192/30
match=35.156.191.128/30
match=54.65.63.192/30
match=54.169.127.128/30
match=54.252.254.64/30
match=177.71.206.192/30
